projobs/profissionais/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required

from .views import CadastroView, ProfissionalHomeView


urlpatterns = patterns('',
    url(r'^$', login_required(ProfissionalHomeView.as_view()), name='home'),
    url(r'^cadastro/$', CadastroView.as_view(), name='cadastro'),
)

projobs/projobs/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from .views import HomeView
admin.autodiscover()


urlpatterns = patterns('',
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^grappelli/', include('grappelli.urls')),
    url(
        r'^profissionais/',
        include('profissionais.urls', namespace='profissionais')
    ),
    url(
        r'^empresas/',
        include('empresas.urls', namespace='empresas')
    ),
    url(
        r'^vagas/',
        include('vagas.urls', namespace='vagas')
    ),

    url(r'^login/$', 'django.contrib.auth.views.login', {
            'template_name': 'login.html'
        }, name='login'
    ),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {
            'template_name': 'logout.html', 'next_page': '/'
        }, name='logout'
    ),

    url(r'^accounts/', include('accounts.urls', namespace='accounts')),

    url(r'^admin/', include(admin.site.urls)),
)

projobs/vagas/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required

from .views import CadastroView, VagaListView, AtualizarView, InscricaoView


urlpatterns = patterns('',
    url(r'^$', VagaListView.as_view(), name='lista'),
    url(
        r'^cadastro/$',
        login_required(CadastroView.as_view()),
        name='cadastro'
    ),
    url(
        r'^atualizar/(?P<pk>\d+)$',
        login_required(AtualizarView.as_view()),
        name='atualizar'
    ),
    url(
        r'^inscricao/(?P<pk>\d+)/$',
        login_required(InscricaoView.as_view()),
        name='inscricao'
    ),
)

projobs/profissionais/models.py
# -*- coding: utf-8 -*-

from django.db import models

from accounts.models import User


class Profissional(User):
    rg = models.CharField(max_length=200, blank=True, null=True)
    cpf = models.CharField(max_length=200, blank=True, null=True)
    data_nascimento = models.DateField()
    telefone = models.CharField(max_length=200, blank=True, null=True)

    class Meta:
        verbose_name_plural = u'Profissionais'

    def __unicode__(self):
        return self.get_full_name()


class FormacaoProfissional(models.Model):
    profissional = models.ForeignKey('Profissional')

    empresa = models.CharField(max_length=200)
    cargo = models.CharField(max_length=200)
    inicio = models.DateField()
    termino = models.DateField(blank=True, null=True)
    atual = models.BooleanField()

    class Meta:
        verbose_name_plural = u'Formações Profissionais'

    def __unicode__(self):
        return u'{} ({} em {})'.format(self.profissional, self.cargo,
                                       self.empresa)

    # to do on forms
    # def clean_termino(self, *args, **kwargs):
    #     if self.cleaned_data['termino'] < self.cleaned_data['inicio']:
    #         raise forms.ValidationError("""
    #             A data de término não pode ser depois da data de início.
    #         """)


class FormacaoAcademica(models.Model):
    profissional = models.ForeignKey('Profissional')

    curso = models.CharField(max_length=200)
    instituicao = models.CharField(max_length=200)
    data_conclusao = models.DateField(blank=True, null=True)

    class Meta:
        verbose_name_plural = u'Formações Acadêmicas'

    def __unicode__(self):
        return u'{} ({} em {})'.format(self.profissional, self.curso,
                                       self.instituicao)

projobs/vagas/models.py
# -*- coding: utf-8 -*-

from django.db import models


class Vaga(models.Model):
    empresa = models.ForeignKey('empresas.Empresa')

    cargo = models.CharField(max_length=200)
    descricao = models.TextField()
    setor = models.CharField(max_length=200)
    inicio = models.DateField(blank=True, null=True)
    quantidade = models.PositiveSmallIntegerField(default=1)
    requisitos = models.ManyToManyField('Requisito', blank=True, null=True)

    def __unicode__(self):
        return u'{} em {}'.format(self.cargo, self.empresa.company_name)


class ProcessoSeletivo(models.Model):
    vaga = models.ForeignKey('Vaga')
    profissionais = models.ManyToManyField(
        'profissionais.Profissional',
        through='Inscricao'
    )
    ativo = models.BooleanField(default=True)

    def __unicode__(self):
        return u'{} - {}'.format(self.vaga.empresa, self.vaga.cargo)


class Inscricao(models.Model):
    SITUACAO_CHOICES = (
        (0, 'Em processo'),
        (1, 'Aprovado'),
        (2, 'Reprovado'),
    )
    processo_seletivo = models.ForeignKey('ProcessoSeletivo')
    profissional = models.ForeignKey('profissionais.Profissional')

    data = models.DateField(auto_now_add=True)
    pretensao_salarial = models.CharField(max_length=200)
    nota_escrita = models.PositiveSmallIntegerField(blank=True, null=True)
    nota_dinamica = models.PositiveSmallIntegerField(blank=True, null=True)
    nota_curriculo = models.PositiveSmallIntegerField(blank=True, null=True)
    requisitos = models.ManyToManyField('Requisito', blank=True, null=True)
    situacao = models.IntegerField(choices=SITUACAO_CHOICES, default=0)

    class Meta:
        verbose_name_plural = u'Inscrições'
        unique_together = ('profissional', 'processo_seletivo')

    def __unicode__(self):
        return u'{} em {}'.format(self.profissional, self.processo_seletivo)


class Entrevista(models.Model):
    inscricao = models.ForeignKey('Inscricao')

    relatorio = models.TextField()

    def __unicode__(self):
        return u'relatório de {}'.format(self.inscricao)


class Requisito(models.Model):
    requisito = models.CharField(max_length=200)

    def __unicode__(self):
        return self.requisito

projobs/profissionais/forms.py
# -*- coding: utf-8 -*-

from django import forms

from accounts.forms import AccountForm
from .models import Profissional


class ProfissionalForm(AccountForm):
    data_nascimento = forms.DateField(
        widget=forms.TextInput(attrs={'id': 'datepicker'})
    )

    class Meta:
        model = Profissional
        fields = (
            'first_name', 'last_name', 'username', 'password1', 'password2',
            'email', 'data_nascimento', 'telefone', 'rg', 'cpf', 'area',
            'estado', 'cidade', 'logradouro'
        )

projobs/profissionais/views.py
# -*- coding: utf-8 -*-

from django.conf import settings
from django.contrib import messages
from django.shortcuts import render, redirect
from django.views.generic import CreateView, DetailView

from .forms import ProfissionalForm
from .models import Profissional


class ProfissionalBaseMixin(object):
    def dispatch(self, request, *args, **kwargs):
        try:
            self.get_object()
        except Profissional.DoesNotExist:
            return redirect('{}?next={}'.format(
                settings.LOGIN_URL,
                request.path
            ))
        return super(ProfissionalBaseMixin, self).dispatch(
            request, *args, **kwargs
        )

    def get_object(self, queryset=None):
        return Profissional.objects.get(pk=self.request.user.pk)


class ProfissionalHomeView(ProfissionalBaseMixin, DetailView):
    model = Profissional
    template_name = 'profissionais/home.html'
    context_object_name = 'profissional'


class CadastroView(CreateView):
    form_class = ProfissionalForm
    template_name = 'profissionais/cadastro.html'
    success_url = '/'

    def form_valid(self, form):
        response = super(CadastroView, self).form_valid(form)
        self.object.send_activation_email()
        messages.success(
            self.request,
            "Foi enviada uma mensagem de ativação para seu e-mail. "
            "Favor verificar"
        )
        return response

projobs/profissionais/templates/profissionais/cadastro.html
{% extends "base/base_forms.html" %}

{% load bootstrap3 %}


{% block title %}
  <h3>{% bootstrap_icon "check" %} Cadastro de Profissional</h3>
  <hr />
{% endblock %}


{% block content %}
  <form class="form" method="POST" role="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    <div class="form-actions">
      <button class="btn btn-primary">Enviar Cadastro</button>
    </div>
  </form>
{% endblock %}

projobs/profissionais/templates/profissionais/home.html
{% extends "base/base.html" %}

{% load bootstrap3 %}

{% block title %}
  <h3>
    {% if profissional.get_full_name %}
      {{ profissional.get_full_name }}
    {% else %}
      Profissional
    {% endif %}
  </h3>
  <hr />
{% endblock %}

{% block content %}

  <table class="table table-bordered">
    <tr class="alert-success"><th colspan="6">Processos ativos</th></tr>
    <tr>
      <th>Cargo</th>
      <th>Setor</th>
      <th>Nota Escrita/Oral</th>
      <th>Nota Dinâmica</th>
      <th>Nota Currículo</th>
      <td class="text-center">Situação</td>
    </tr>
    {% for inscricao in profissional.inscricao_set.all %}
      {% if inscricao.processo_seletivo.ativo %}
        <tr>
          <td>{{ inscricao.processo_seletivo.vaga.cargo }}</td>
          <td>{{ inscricao.processo_seletivo.vaga.setor }}</td>
          <td>{% if inscricao.nota_escrita %}{{ inscricao.nota_escrita }}{% endif %}</td>
          <td>{% if inscricao.nota_dinamica %}{{ inscricao.nota_dinamica }}{% endif %}</td>
          <td>{% if inscricao.nota_curriculo %}{{ inscricao.nota_curriculo }}{% endif %}</td>
          <td title="{{ inscricao.get_situacao_display }}" class="text-center">
            {% if inscricao.situacao == 0 %}
              <div class="text-warning">{% bootstrap_icon "bell" %}</div>
            {% elif inscricao.situacao == 1 %}
              <div class="text-success">{% bootstrap_icon "thumbs-up" %}</div>
            {% else %}
              <div class="text-danger">{% bootstrap_icon "thumbs-down" %}</div>
            {% endif %}
          </td>
        </tr>
      {% endif %}
    {% endfor %}
  </table>

  <hr />

  <table class="table table-bordered">
    <tr class="alert-warning"><th colspan="6">Processos inativos</th></tr>
    <tr>
      <th>Cargo</th>
      <th>Setor</th>
      <th>Nota Escrita/Oral</th>
      <th>Nota Dinâmica</th>
      <th>Nota Currículo</th>
      <td class="text-center">Situação</td>
    </tr>
    {% for inscricao in profissional.inscricao_set.all %}
      {% if not inscricao.processo_seletivo.ativo %}
        <tr>
          <td>{{ inscricao.processo_seletivo.vaga.cargo }}</td>
          <td>{{ inscricao.processo_seletivo.vaga.setor }}</td>
          <td>{% if inscricao.nota_escrita %}{{ inscricao.nota_escrita }}{% endif %}</td>
          <td>{% if inscricao.nota_dinamica %}{{ inscricao.nota_dinamica }}{% endif %}</td>
          <td>{% if inscricao.nota_curriculo %}{{ inscricao.nota_curriculo }}{% endif %}</td>
          <td title="{{ inscricao.get_situacao_display }}" class="text-center">
            {% if inscricao.situacao == 0 %}
              <div class="text-warning">{% bootstrap_icon "bell" %}</div>
            {% elif inscricao.situacao == 1 %}
              <div class="text-success">{% bootstrap_icon "thumbs-up" %}</div>
            {% else %}
              <div class="text-danger">{% bootstrap_icon "thumbs-down" %}</div>
            {% endif %}
          </td>
        </tr>
      {% endif %}
    {% endfor %}
  </table>

{% endblock %}