projobs/projobs/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from .views import HomeView
admin.autodiscover()


urlpatterns = patterns('',
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^grappelli/', include('grappelli.urls')),
    url(
        r'^profissionais/',
        include('profissionais.urls', namespace='profissionais')
    ),
    url(
        r'^empresas/',
        include('empresas.urls', namespace='empresas')
    ),
    url(
        r'^vagas/',
        include('vagas.urls', namespace='vagas')
    ),

    url(r'^login/$', 'django.contrib.auth.views.login', {
            'template_name': 'login.html'
        }, name='login'
    ),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {
            'template_name': 'logout.html', 'next_page': '/'
        }, name='logout'
    ),

    url(r'^accounts/', include('accounts.urls', namespace='accounts')),

    url(r'^admin/', include(admin.site.urls)),
)

projobs/vagas/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required

from .views import CadastroView, VagaListView, AtualizarView, InscricaoView


urlpatterns = patterns('',
    url(r'^$', VagaListView.as_view(), name='lista'),
    url(
        r'^cadastro/$',
        login_required(CadastroView.as_view()),
        name='cadastro'
    ),
    url(
        r'^atualizar/(?P<pk>\d+)$',
        login_required(AtualizarView.as_view()),
        name='atualizar'
    ),
    url(
        r'^inscricao/(?P<pk>\d+)/$',
        login_required(InscricaoView.as_view()),
        name='inscricao'
    ),
)

projobs/vagas/models.py
# -*- coding: utf-8 -*-

from django.db import models


class Vaga(models.Model):
    empresa = models.ForeignKey('empresas.Empresa')

    cargo = models.CharField(max_length=200)
    descricao = models.TextField()
    setor = models.CharField(max_length=200)
    inicio = models.DateField(blank=True, null=True)
    quantidade = models.PositiveSmallIntegerField(default=1)
    requisitos = models.ManyToManyField('Requisito', blank=True, null=True)

    def __unicode__(self):
        return u'{} em {}'.format(self.cargo, self.empresa.company_name)


class ProcessoSeletivo(models.Model):
    vaga = models.ForeignKey('Vaga')
    profissionais = models.ManyToManyField(
        'profissionais.Profissional',
        through='Inscricao'
    )
    ativo = models.BooleanField(default=True)

    def __unicode__(self):
        return u'{} - {}'.format(self.vaga.empresa, self.vaga.cargo)


class Inscricao(models.Model):
    SITUACAO_CHOICES = (
        (0, 'Em processo'),
        (1, 'Aprovado'),
        (2, 'Reprovado'),
    )
    processo_seletivo = models.ForeignKey('ProcessoSeletivo')
    profissional = models.ForeignKey('profissionais.Profissional')

    data = models.DateField(auto_now_add=True)
    pretensao_salarial = models.CharField(max_length=200)
    nota_escrita = models.PositiveSmallIntegerField(blank=True, null=True)
    nota_dinamica = models.PositiveSmallIntegerField(blank=True, null=True)
    nota_curriculo = models.PositiveSmallIntegerField(blank=True, null=True)
    requisitos = models.ManyToManyField('Requisito', blank=True, null=True)
    situacao = models.IntegerField(choices=SITUACAO_CHOICES, default=0)

    class Meta:
        verbose_name_plural = u'Inscrições'
        unique_together = ('profissional', 'processo_seletivo')

    def __unicode__(self):
        return u'{} em {}'.format(self.profissional, self.processo_seletivo)


class Entrevista(models.Model):
    inscricao = models.ForeignKey('Inscricao')

    relatorio = models.TextField()

    def __unicode__(self):
        return u'relatório de {}'.format(self.inscricao)


class Requisito(models.Model):
    requisito = models.CharField(max_length=200)

    def __unicode__(self):
        return self.requisito

projobs/vagas/forms.py
# -*- coding: utf-8 -*-

from django import forms

from .models import Vaga, Inscricao


class VagaForm(forms.ModelForm):
    inicio = forms.DateField(
        widget=forms.TextInput(attrs={'id': 'datepicker'})
    )

    class Meta:
        model = Vaga
        exclude = ('empresa', )


class InscricaoForm(forms.ModelForm):
    class Meta:
        model = Inscricao
        fields = ('pretensao_salarial', 'requisitos')

projobs/vagas/views.py
from django.core.urlresolvers import reverse_lazy
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import CreateView, ListView, UpdateView

from empresas.views import EmpresaBaseMixin
from profissionais.views import ProfissionalBaseMixin
from .forms import VagaForm, InscricaoForm
from .models import Vaga, Inscricao


class CadastroView(EmpresaBaseMixin, CreateView):
    model = Vaga
    template_name = 'vagas/cadastro.html'
    form_class = VagaForm
    success_url = reverse_lazy('empresas:home')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.empresa_id = self.get_object().pk
        self.object.save()
        form.save_m2m()
        messages.success(self.request, 'Vaga cadastrada com sucesso!')
        return HttpResponseRedirect(self.get_success_url())


class VagaListView(ListView):
    model = Vaga
    context_object_name = 'vagas'


class AtualizarView(EmpresaBaseMixin, UpdateView):
    model = Vaga
    form_class = VagaForm
    success_url = reverse_lazy('empresas:home')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.empresa_id = self.empresa_id
        self.object.save()
        form.save_m2m()
        messages.success(self.request, 'Vaga atualizada com sucesso!')
        return HttpResponseRedirect(self.get_success_url())

    def get_object(self, queryset=None):
        obj = super(AtualizarView, self).get_object(queryset)
        self.empresa_id = obj.pk
        return obj.vaga_set.get(pk=self.kwargs.get('pk'))


class InscricaoView(ProfissionalBaseMixin, CreateView):
    model = Inscricao
    form_class = InscricaoForm
    success_url = reverse_lazy('profissionais:home')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.processo_seletivo_id = self.kwargs.get('pk')
        self.object.profissional_id = self.request.user.pk
        self.object.save()
        form.save_m2m()
        messages.success(self.request, 'Inscrição realizada. Boa sorte!')
        return HttpResponseRedirect(self.get_success_url())

projobs/vagas/templates/vagas/cadastro.html
{% extends "base/base_forms.html" %}

{% load bootstrap3 %}


{% block title %}
  <h3>{% bootstrap_icon "check" %} Cadastro de Vaga</h3>
  <hr />
{% endblock %}


{% block content %}
  <form class="form" method="POST" role="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    <div class="form-actions">
      <button class="btn btn-primary">Criar Vaga</button>
    </div>
  </form>
{% endblock %}

projobs/vagas/templates/vagas/inscricao_form.html
{% extends "base/base.html" %}

{% load bootstrap3 %}


{% block title %}
  <h3>{% bootstrap_icon "check" %} Inscrição</h3>
  <hr />
{% endblock %}


{% block content %}
  <form class="form" method="POST" role="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    <div class="form-actions">
      <button class="btn btn-primary">Enviar inscrição</button>
    </div>
  </form>
{% endblock %}

projobs/vagas/templates/vagas/vaga_form.html
{% extends "base/base_forms.html" %}

{% load bootstrap3 %}


{% block title %}
  <h3>{% bootstrap_icon "check" %} Atualizar Vaga</h3>
  <hr />
{% endblock %}


{% block content %}
  <form class="form" method="POST" role="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    <div class="form-actions">
      <button class="btn btn-primary">Atualizar</button>
    </div>
  </form>
{% endblock %}

projobs/vagas/templates/vagas/vaga_list.html
{% extends "base/base.html" %}

{% load bootstrap3 %}


{% block title %}<h3>{% bootstrap_icon "list" %} Vagas</h3>{% endblock %}

{% block content %}
  <table class="table table-bordered">
    <tr>
      <th>Cargo</th>
      <th>Setor</th>
      <th>Requisitos</th>
      <th>Inscrição</th>
    </tr>
    {% for vaga in vagas %}
      <tr>
        <td>{{ vaga.cargo }}</td>
        <td>{{ vaga.setor }}</td>
        <td>
          {% if vaga.requisitos.exists %}
            <button class="btn btn-default" title="Clique para visualizar os requisitos necessários para essa vaga" data-toggle="modal" data-target="#RequisitosModal{{ forloop.counter0 }}">{% bootstrap_icon "question-sign" %}
            </button>
            <!-- Modal -->
            <div class="modal fade" id="RequisitosModal{{ forloop.counter0 }}" tabindex="-1" role="dialog" aria-labelledby="RequisitosLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="RequisitosLabel">Requistos da vaga: {{ vaga.cargo|capfirst }}</h4>
                  </div>
                  <div class="modal-body">
                    <ul class="list-unstyled">
                    {% for requisito in vaga.requisitos.all %}
                      <li>{{ requisito }}</li>
                    {% endfor %}
                    </ul>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <a href="{% url 'vagas:inscricao' vaga.pk %}" class="btn btn-primary{% if not vaga.processoseletivo_set.exists %} disabled{% endif %}">Quero me inscrever</a>
                  </div>
                </div><!-- /.modal-content -->
              </div><!-- /.modal-dialog -->
            </div><!-- /.modal -->
          {% else %}
            <button class="btn btn-default disabled" title="Não há requisitos para essa vaga">{% bootstrap_icon "question-sign" %}</button>
          {% endif %}
        </td>
        <td>
          <a href="{% url 'vagas:inscricao' vaga.pk %}" class="btn btn-primary{% if not vaga.processoseletivo_set.exists %} disabled{% endif %}">Inscrição</a>
        </td>
      </tr>
    {% endfor %}
  </table>
{% endblock %}