projobs/projobs/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from .views import HomeView
admin.autodiscover()


urlpatterns = patterns('',
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^grappelli/', include('grappelli.urls')),
    url(
        r'^profissionais/',
        include('profissionais.urls', namespace='profissionais')
    ),
    url(
        r'^empresas/',
        include('empresas.urls', namespace='empresas')
    ),
    url(
        r'^vagas/',
        include('vagas.urls', namespace='vagas')
    ),

    url(r'^login/$', 'django.contrib.auth.views.login', {
            'template_name': 'login.html'
        }, name='login'
    ),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {
            'template_name': 'logout.html', 'next_page': '/'
        }, name='logout'
    ),

    url(r'^accounts/', include('accounts.urls', namespace='accounts')),

    url(r'^admin/', include(admin.site.urls)),
)

projobs/vagas/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required

from .views import CadastroView, VagaListView, AtualizarView, InscricaoView


urlpatterns = patterns('',
    url(r'^$', VagaListView.as_view(), name='lista'),
    url(
        r'^cadastro/$',
        login_required(CadastroView.as_view()),
        name='cadastro'
    ),
    url(
        r'^atualizar/(?P<pk>\d+)$',
        login_required(AtualizarView.as_view()),
        name='atualizar'
    ),
    url(
        r'^inscricao/(?P<pk>\d+)/$',
        login_required(InscricaoView.as_view()),
        name='inscricao'
    ),
)

projobs/templates/base/base.html
<!DOCTYPE html>
<html>

<head>
<title>Projobs</title>

<meta name="viewport" content="width=device-width, initial-scale=1.0">

<!-- JQuery -->
<script src="{{ STATIC_URL }}js/jquery-2.0.3.min.js"></script>

<!-- Bootstrap -->
<link rel="stylesheet" href="{{ STATIC_URL }}assets/bootstrap3/css/bootstrap.min.css" />
<script src="{{ STATIC_URL }}assets/bootstrap3/js/bootstrap.min.js"></script>

<!-- Projobs -->
<link rel="stylesheet" href="{{ STATIC_URL }}css/screen.css" />

{% block extrahead %}
{% endblock %}

</head>

<body>
<div class="container">
  <div class="header">
    <ul class="nav nav-pills pull-right">
      <li><a href="{% url 'home' %}">Home</a></li>
      <li><a href="{% url 'profissionais:home' %}">Profissional</a></li>
      <li><a href="{% url 'empresas:home' %}">Empresa</a></li>
      {% if user.is_authenticated %}
        <li class="active"><a href="{% url 'logout' %}">Sair</a></li>
      {% else %}
        <li class="active"><a href="{% url 'login' %}">Entrar</a></li>
      {% endif %}
    </ul>
    <h3 class="text-muted">
      <a href="{% url 'home' %}">Projobs
        <span class="glyphicon glyphicon-thumbs-up"></span>
      </a>
    </h3>
  </div>
  <hr />

  {% block jumbotron %}
  {% endblock %}

  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">{{ message }}</div>
        {% endfor %}
      {% endif %}
      {% block title %}{% endblock %}

      {% block content %}
      {% endblock %}
    </div>
  </div>

  <hr />

</div>
</body>

</html>

projobs/templates/base/base_forms.html
{% extends "base/base.html" %}


{% block extrahead %}
<script src="{{ STATIC_URL }}assets/bootstrap-datetimepicker/js/bootstrap-datetimepicker.js"></script>
<script src="{{ STATIC_URL }}assets/bootstrap-datetimepicker/js/locales/bootstrap-datetimepicker.pt-BR.js"></script>
<script>
  $(function () {
    $('#datepicker').datetimepicker({
        pickTime: false,
        language: 'pt-BR',
        format: 'dd/MM/yyyy'
    });
  });
</script>
{% endblock %}