projobs/projobs/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from .views import HomeView
admin.autodiscover()


urlpatterns = patterns('',
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^grappelli/', include('grappelli.urls')),
    url(
        r'^profissionais/',
        include('profissionais.urls', namespace='profissionais')
    ),
    url(
        r'^empresas/',
        include('empresas.urls', namespace='empresas')
    ),
    url(
        r'^vagas/',
        include('vagas.urls', namespace='vagas')
    ),

    url(r'^login/$', 'django.contrib.auth.views.login', {
            'template_name': 'login.html'
        }, name='login'
    ),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {
            'template_name': 'logout.html', 'next_page': '/'
        }, name='logout'
    ),

    url(r'^accounts/', include('accounts.urls', namespace='accounts')),

    url(r'^admin/', include(admin.site.urls)),
)

projobs/vagas/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required

from .views import CadastroView, VagaListView, AtualizarView, InscricaoView


urlpatterns = patterns('',
    url(r'^$', VagaListView.as_view(), name='lista'),
    url(
        r'^cadastro/$',
        login_required(CadastroView.as_view()),
        name='cadastro'
    ),
    url(
        r'^atualizar/(?P<pk>\d+)$',
        login_required(AtualizarView.as_view()),
        name='atualizar'
    ),
    url(
        r'^inscricao/(?P<pk>\d+)/$',
        login_required(InscricaoView.as_view()),
        name='inscricao'
    ),
)

projobs/templates/home.html
{% extends "base/base.html" %}

{% block content %}
  <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
    <div class="panel panel-success">
      <div class="panel-heading">
        <h3 class="panel-title">Profissional</h3>
      </div>
      <div class="panel-body">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec interdum, arcu in pharetra tincidunt, quam sem suscipit nisi, eu feugiat est massa eget est. Curabitur id iaculis mi, eget posuere massa. Donec non faucibus sem, eu ornare lorem. Curabitur eleifend est ac velit tempor, sit amet venenatis velit pharetra. Nunc ac imperdiet orci. Pellentesque quis lectus ullamcorper, pharetra odio non, mollis ligula. Duis id turpis ultricies, molestie ipsum nec, mollis mauris. Curabitur posuere congue ligula non tincidunt. Suspendisse a nibh vulputate, tristique metus ullamcorper, imperdiet purus. Sed lobortis ullamcorper est, non sodales erat interdum id. In sagittis nisl faucibus, vestibulum sem ut, vulputate elit.
        <hr />
        <a href="{% url 'profissionais:cadastro' %}"><button class="btn btn-success">Cadastrar Profissional</button></a>
        <a href="{% url 'vagas:lista' %}"><button class="btn btn-success pull-right">Visualizar Vagas</button></a>
      </div>
    </div>
  </div>

  <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title">Empresa</h3>
      </div>
      <div class="panel-body">
        Nulla quis leo nisi. Vivamus sed orci neque. Mauris tincidunt aliquam massa id congue. Quisque in lorem erat. Aliquam at volutpat dui. Aenean at pretium tellus. Phasellus vel sem eget leo ullamcorper imperdiet eu in erat. Vestibulum sagittis nunc eros, sed consectetur purus sagittis lacinia. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Integer sed augue ornare, tempor enim quis, ultrices nisi. Fusce eleifend sagittis sapien, sit amet blandit dui hendrerit at. Donec viverra urna eget eros lacinia, vel aliquet nisi ultricies. Vivamus facilisis risus vel massa convallis pharetra.
        <hr />
        <a href="{% url 'empresas:cadastro' %}"><button class="btn btn-primary">Cadastrar Empresa</button></a>
      </div>
    </div>
  </div>
{% endblock %}

projobs/templates/login.html
{% extends "base/base.html" %}

{% load bootstrap3 %}


{% block content %}
<div class="col-lg-4">
</div>
<div class="col-lg-4">
  <form class="form-signin" method="POST">
    {% csrf_token %}
    <input type="hidden" name="next" value="{% url 'home' %}" />
    <h2 class="form-signin-heading">Por favor, acesse</h2>
    {% bootstrap_form form %}
    <button class="btn btn-primary btn-block btn-lg">Acessar</button>
  </form>
</div>
<div class="col-lg-4">
</div>
{% endblock %}

projobs/templates/logout.html
{% extends "base/base.html" %}

{% load bootstrap3 %}


{% block content %}
<h3>Você saiu. Obrigado por utilizar nosso sistema!</h3>
{% endblock %}